path: /home/maohika/work/ika/dataset/ocr/char_type
train: train
val: val

nc: 8
names: [
  'ocr_hiragana',
  'ocr_katakana',
  'ocr_number',
  'ocr_alphabet',
  'ocr_symbol',
  'ocr_greek',
  'ocr_rusian',
  'ocr_diacritical'
]