path: /home/maohika/work/ika/dataset/battle_indicator
train: train
val: val

nc: 37
names: [
  'indicator_count',
  'indicator_area_occupancy',
  'indicator_lead',
  'indicator_count_lead',
  'indicator_count_behind',
  'indicator_count_stop',
  'indicator_count_stopped',
  'indicator_area_secure',
  'indicator_area_secured',
  'indicator_penalty',
  'indicator_result_win',
  'indicator_result_lose',
  'indicator_result_judge',
  'indicator_result_kojudge',
  'indicator_result_count',
  'indicator_result_percent',
  'indicator_result_knockout',
  'indicator_asari_team_total',
  'indicator_asari_mine_total',
  'indicator_asari_mine_gachi',
  'indicator_asari_barrier_break',
  'indicator_asari_barrier_broken',
  'indicator_asari_barrier_repair',
  'indicator_asari_barrier_repaired',
  'indicator_hoko_get',
  'indicator_hoko_lost',
  'indicator_hoko_robbed',
  'indicator_hoko_stop',
  'indicator_barrier_pass',
  'indicator_barrier_passed',
  'indicator_nawabari_paintpoint',
  'indicator_yagura_get',
  'indicator_yagura_robbed',
  'indicator_yagura_return',
  'indicator_yagura_returned',
  'indicator_yagura_barrier_reach',
  'indicator_yagura_barrier_reached'
]
