path: /home/maohika/work/ika/dataset/stage
train: train
val: val

nc: 30
names: [
  'stage_amabi_onion',
  'stage_cyozame_drop',
  'stage_gonzui_vending_machine',
  'stage_hirame_room',
  'stage_cyozame_crane',
  'stage_kinmedai_table',
  'stage_kinmedai_center_table',
  'stage_konbu_wall',
  'stage_kusaya_light',
  'stage_mahimahi_speaker',
  'stage_mantamaria_mast',
  'stage_mantamaria_rope',
  'stage_masaba_bridge',
  'stage_mategai_pillar',
  'stage_namerou_car',
  'stage_namerou_truck',
  'stage_nampula_sheet',
  'stage_ohyou_head',
  'stage_ohyou_tail',
  'stage_sumeshi_wheel',
  'stage_sumeshi_rocket',
  'stage_sumeshi_rail',
  'stage_takaashi_crane',
  'stage_taraport_sculture',
  'stage_yagara_flag',
  'stage_yunohana_stone',
  'stage_zatou_board',
  'stage_kusaya_bamboo',
  'stage_bangaitei_board',
  'stage_negitoro_reel'
]
