from move_classification_files import move_files

kana_list = [
    'greek_alpha',
    'greek_beta',
    'greek_gamma',
    'greek_delta',
    'greek_epsilon',
    'greek_zeta',
    'greek_eta',
    'greek_theta',
    'greek_iota',
    'greek_kappa',
    'greek_lambda',
    'greek_mu',
    'greek_nu',
    'greek_xi',
    'greek_omicron',
    'greek_pi',
    'greek_rho',
    'greek_sigma',
    'greek_tau',
    'greek_upsilon',
    'greek_phi',
    'greek_chi',
    'greek_psi',
    'greek_omega',
    'greek_alpha_upper',
    'greek_beta_upper',
    'greek_gamma_upper',
    'greek_delta_upper',
    'greek_epsilon_upper',
    'greek_zeta_upper',
    'greek_eta_upper',
    'greek_theta_upper',
    'greek_iota_upper',
    'greek_kappa_upper',
    'greek_lambda_upper',
    'greek_mu_upper',
    'greek_nu_upper',
    'greek_xi_upper',
    'greek_omicron_upper',
    'greek_pi_upper',
    'greek_rho_upper',
    'greek_sigma_upper',
    'greek_tau_upper',
    'greek_upsilon_upper',
    'greek_phi_upper',
    'greek_chi_upper',
    'greek_psi_upper',
    'greek_omega_upper',
]

src_dir = '/Users/maohika/Downloads/char/greek/{label}'
dst_dir = '/Volumes/splatoon3/dataset/ocr/greek/{label}'
move_files(kana_list, src_dir, dst_dir)
