from move_classification_files import move_files

label_list = [
    'alphabet_a',
    'alphabet_b',
    'alphabet_c',
    'alphabet_d',
    'alphabet_e',
    'alphabet_f',
    'alphabet_g',
    'alphabet_h',
    'alphabet_i',
    'alphabet_j',
    'alphabet_k',
    'alphabet_l',
    'alphabet_m',
    'alphabet_n',
    'alphabet_o',
    'alphabet_p',
    'alphabet_q',
    'alphabet_r',
    'alphabet_s',
    'alphabet_t',
    'alphabet_u',
    'alphabet_v',
    'alphabet_w',
    'alphabet_x',
    'alphabet_y',
    'alphabet_z',
    'alphabet_a_upper',
    'alphabet_b_upper',
    'alphabet_c_upper',
    'alphabet_d_upper',
    'alphabet_e_upper',
    'alphabet_f_upper',
    'alphabet_g_upper',
    'alphabet_h_upper',
    'alphabet_i_upper',
    'alphabet_j_upper',
    'alphabet_k_upper',
    'alphabet_l_upper',
    'alphabet_m_upper',
    'alphabet_n_upper',
    'alphabet_o_upper',
    'alphabet_p_upper',
    'alphabet_q_upper',
    'alphabet_r_upper',
    'alphabet_s_upper',
    'alphabet_t_upper',
    'alphabet_u_upper',
    'alphabet_v_upper',
    'alphabet_w_upper',
    'alphabet_x_upper',
    'alphabet_y_upper',
    'alphabet_z_upper'
]

src_dir = '/Users/maohika/Downloads/char/alphabet/{label}'
dst_dir = '/Volumes/splatoon3/dataset/ocr/alphabet/{label}'
move_files(label_list, src_dir, dst_dir)