from move_classification_files import move_files

label_list = [
    'symbol_amp',
    'symbol_asterisk_small',
    'symbol_diamond_stroke',
    'symbol_dot',
    'symbol_exclamation',
    'symbol_hyphen',
    'symbol_implies',
    'symbol_left_corner_bracket',
    'symbol_left_round_bracket',
    'symbol_left_square_bracket_large',
    'symbol_left_square_bracket_small',
    'symbol_percent',
    'symbol_registered_trademark',
    'symbol_right_corner_bracket',
    'symbol_right_round_bracket',
    'symbol_right_square_bracket_large',
    'symbol_right_square_bracket_small',
    'symbol_semicolon',
    'symbol_sharp',
    'symbol_single_dash',
    'symbol_slash',
    'symbol_star_stroke',
    'symbol_tilde',
    'symbol_kuten',
    'symbol_backquote',
    'symbol_infinity',
    'symbol_star_fill',
    'symbol_eighth_note',
    'symbol_double_dash',
    'symbol_diamond_fill',
    'symbol_root',
    'symbol_superset',
    'symbol_equal',
    'symbol_dollar',
    'symbol_hat',
    'symbol_greater_than',
    'symbol_less_than',
    'symbol_dagger',
    'symbol_forall',
    'symbol_because',
    'symbol_yen',
    'symbol_arrow_left',
    'symbol_arrow_right',
    'symbol_arrow_up',
    'symbol_arrow_down',
    'symbol_question',
    'symbol_pound',
    'symbol_circle_double',
    'symbol_colon',
    'symbol_euro',
    'symbol_identical',
    'symbol_man',
    'symbol_multiply',
    'symbol_number',
    'symbol_plus',
    'symbol_postal',
    'symbol_question_reverse',
    'symbol_section',
    'symbol_sime',
    'symbol_touten',
    'symbol_asterisk_large',
    'symbol_copyright',
]

src_dir = '/Users/maohika/Downloads/char/symbol/{label}'
dst_dir = '/Volumes/splatoon3/dataset/ocr/symbol/{label}'
move_files(label_list, src_dir, dst_dir)
